server:
  port: 8200
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graduation?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: LFQ13459726059
    driver-class-name: com.mysql.jdbc.Driver